
baseURL = "https://fieldpacks.fr"
languageCode = "fr"
DefaultContentLanguage = "fr"
theme = "less"
googleAnalytics = ""
RemovePathAccents = true
timeout = 200000
enableRobotsTXT = true
canonifyURLs = true
paginate = 12


[author]
  name = "FIELDPACKS"

[build]
  writeStats = true

[permalinks]
  posts = "/:slug"
  categories = "/:slug"
  projects = "/:slug"

[imaging]
  resampleFilter = "lanczos"

[params]
  sizes = [ "2048" , "1024" , "512" ]
  tags = []

  sansSerifFont = "times new roman"
  titleFont = "roboto"
  bodyFont = "times new roman"

  hasLogo = true
  accentColor = "#C4912A"

#heroHeader = false

[taxonomies]
  category = "categories"

[params.titles]
  posts = "Journal"
  categories = "Catégories"

[params.social]
  email = "hello@fieldpacks.fr"
  domain = "FIELDPACKS"
  instagram = "fieldpacks"

  [[menu.main]]
    name = "Sacoches"
    title = "Sacoches"
    weight = 1
    identifier = "sacoches"
    url = "/sacoches"
  [[menu.main]]
    name = "Informations Techniques"
    title = "Informations Techniques"
    weight = 2
    identifier = "informations"
    url = "/informations"
[[menu.main]]
  name = "À Propos"
  title = "À Propos"
  weight = 3
  identifier = "now"
  url = "/now"

[[related.indices]]
  name = "categories"
  weight =  1 # We don't really need this, but omitting it would disable the indice.
  includeNewer = true
